name: aoc2022
description: A pacakge of Dart solutions for Advent of Code 2022
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  trotter: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
